// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVUkMDKmitGG2U3HnBiRZ8NtuHPSlMKps',
    appId: '1:824435466912:web:7d7ce4fba179704aeb9fc5',
    messagingSenderId: '824435466912',
    projectId: 'skill-manage1',
    authDomain: 'skill-manage1.firebaseapp.com',
    storageBucket: 'skill-manage1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEOYwoRN44YZgmBjwJXDR21HfvQk5YT4',
    appId: '1:824435466912:android:0884ac21390eb2bceb9fc5',
    messagingSenderId: '824435466912',
    projectId: 'skill-manage1',
    storageBucket: 'skill-manage1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXqEznlWZmcsSDef_raIHigJcEi0rrIc0',
    appId: '1:824435466912:ios:45e06cdcb6157c33eb9fc5',
    messagingSenderId: '824435466912',
    projectId: 'skill-manage1',
    storageBucket: 'skill-manage1.firebasestorage.app',
    iosClientId: '824435466912-e80kh39llmhn0lpkhk7m6o0sr650e0on.apps.googleusercontent.com',
    iosBundleId: 'com.jrhbusinesss.skillmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXqEznlWZmcsSDef_raIHigJcEi0rrIc0',
    appId: '1:824435466912:ios:5931c4200966da62eb9fc5',
    messagingSenderId: '824435466912',
    projectId: 'skill-manage1',
    storageBucket: 'skill-manage1.firebasestorage.app',
    iosBundleId: 'com.example.skillManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVUkMDKmitGG2U3HnBiRZ8NtuHPSlMKps',
    appId: '1:824435466912:web:14c6218261d3bc39eb9fc5',
    messagingSenderId: '824435466912',
    projectId: 'skill-manage1',
    authDomain: 'skill-manage1.firebaseapp.com',
    storageBucket: 'skill-manage1.firebasestorage.app',
  );
}